-- ===========================================================================
-- Projeto Sete — Seed de Blog Premium
-- Execute APÓS SUPABASE_SCHEMA.sql e SUPABASE_RLS.sql.
-- ===========================================================================

insert into public.blog_posts (title, slug, excerpt, body, cover_image_url, cover_alt, reading_minutes, tags, author, is_published, is_featured, published_at, seo)
values
  -- 1. Post principal (destaque)
  (
    'Marcenaria Sob Medida: O que Considerar em 2025',
    'marcenaria-sob-medida-2025',
    'Tendências, materiais e ferragens que elevam o resultado final de um projeto planejado. Um guia completo para quem busca excelência em marcenaria residencial e corporativa.',
    'A marcenaria sob medida deixou de ser apenas funcional para se tornar parte da identidade dos ambientes. Em 2025, três pontos merecem atenção especial de arquitetos, designers e incorporadores.\n\n## 1. Materiais em Alta\n\nMadeiras como **freijó** e **carvalho** continuam em alta, agora combinadas a lâminas naturais que reproduzem texturas de madeiras nobres com sustentabilidade. O tauari, alternativa nacional ao mogno, ganha espaço em projetos corporativos por sua durabilidade e tom uniforme.\n\n### Lâminas Naturais vs. Revestimentos Sintéticos\n\nAs lâminas naturais oferecem profundidade visual que nenhum revestimento sintético reproduz. Cada veio é único, cada painel conta uma história. O investimento maior se paga na valorização do imóvel.\n\n| Característica | Lâmina Natural | Revestimento Sintético |\n|----------------|---------------|----------------------|\n| Durabilidade | 20+ anos | 5-8 anos |\n| Reparo | Restaurável | Substituição total |\n| Valor agregado | Alto | Médio |\n\n## 2. Ferragens Premium\n\nFerragens com amortecimento e soft-close são hoje item obrigatório em projetos de alto padrão. Marcas como **Blum**, **Grass** e **Hettich** dominam o mercado com sistemas que garantem durabilidade de 100.000+ ciclos de abertura.\n\n### Sistemas de Abertura\n\n- **Touch-to-open**: Ideal para cozinhas e living, elimina completamente puxadores\n- **Push-to-open magnético**: Versão silenciosa do touch, com imãs ocultos\n- **Sensor elétrico**: Para portas pesadas (acima de 1,20 m), com abertura por toque leve\n\n## 3. Integração com Iluminação\n\nA iluminação embutida na marcenaria é o diferencial que separa um projeto bom de um projeto excepcional. Fitas de LED com temperatura de cor ajustável (2700K a 6500K) permitem criar atmosferas que mudam ao longo do dia.\n\n### Onde Instalar\n\n- **Sancas de painéis**: Luz indireta que destaca a textura da madeira\n- **Nichos escultóricos**: Micro-LED embutido sem pontos aparentes\n- **Rodapés iluminados**: Efeito flutuante em closets e banheiros\n- **Prateleiras de vidro**: LED lateral que faz o vidro brilhar\n\n## Conclusão\n\nInvestir em marcenaria sob medida é investir em qualidade de vida. Em 2025, a tendência é clara: menos móveis soltos, mais marcenaria integrada. Cada ambiente deve ser pensado como um organismo vivo, onde a madeira é a pele e os detalhes, a alma.',
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=85',
    'Detalhe de marcenaria em madeira freijó com iluminação embutida',
    6, '{marcenaria,tendências,2025,guia}'::text[],
    'Felipe Amorim', true, true, now() - interval '14 days',
    '{"title":"Marcenaria Sob Medida 2025: Guia Completo","description":"Descubra as tendências, materiais e ferragens que definem a marcenaria de alto padrão em 2025. Guia completo para arquitetos e designers.","image":"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=85"}'::jsonb
  ),

  -- 2. Post sobre CASACOR
  (
    'O que a CASACOR nos Ensinou sobre o Futuro da Marcenaria',
    'casacor-futuro-marcenaria',
    'A mostra mais importante de arquitetura e design da América Latina revela tendências que vão transformar a forma como pensamos móveis planejados.',
    'Participar da CASACOR é mais do que apresentar um ambiente — é entender para onde o mercado está caminhando. Depois de três edições consecutivas, reunimos os principais aprendizados.\n\n## 1. O Fim do Armário Convencional\n\nAs peças expositoras da CASACOR 2024 mostraram uma verdade incontestável: o armário como conhecemos está com os dias contados. Em seu lugar, painéis monolíticos que escondem compartimentos inteiros, portas que desaparecem nas laterais e nichos que funcionam como esculturas.\n\n### Por que essa mudança?\n\nO morador de alto padrão não quer ver soluções de armazenamento — quer ver espaço, luz e design. A marcenaria precisa servir sem aparecer.\n\n## 2. A Cozinha como Experiência\n\nA cozinha gourmet deixou de ser um cômodo escondido para se tornar o centro das atenções. Mas não da forma óbvia — as cozinhas mais elogiadas da mostra foram aquelas que \"desaparecem\" quando não estão em uso.\n\n> "A cozinha mais bonita que já vi é a que não se vê."\n> — Visitante da CASACOR 2024\n\n### Portas Escamoteáveis\n\nSistemas de ferragens italianas permitem que portas de até 2,80 m de altura corram lateralmente, revelando bancadas completas. Quando fechadas, formam uma parede contínua de marcenaria.\n\n## 3. Closets com Tecnologia\n\nO vidro inteligente (smart glass) foi o grande protagonista dos closets na mostra. Com um toque, o vidro muda de transparente para opaco — permitindo exibir ou esconder o acervo de roupas e acessórios.\n\n### Aplicações Práticas\n\n- **Modo vitrine**: Para dias de organização\n- **Modo privado**: Para visitas inesperadas\n- **Modo noturno**: Iluminação interna suave que funciona como luz de vigília\n\n## 4. A Volta dos Acabamentos Naturais\n\nDepois de anos de domínio dos lacados brilhantes e das superfícies lisas, a CASACOR 2024 marcou o retorno das texturas naturais. Madeira escovada, concreto queimado, cimento queimado e pedras brutas em contraste com metais polidos.\n\n## Conclusão\n\nO futuro da marcenaria é invisível, inteligente e natural. As tendências vistas na CASACOR não são passageiras — são o reflexo de uma mudança profunda na forma como habitamos nossos espaços.',
    'https://images.unsplash.com/photo-1618220179428-22790b461013?w=1200&q=85',
    'Ambiente CASACOR com marcenaria integrada',
    5, '{casacor,tendências,marcenaria,design}'::text[],
    'Felipe Amorim', true, true, now() - interval '10 days',
    '{"title":"O que a CASACOR nos Ensinou sobre o Futuro da Marcenaria","description":"Participar da CASACOR revelou tendências que vão transformar a marcenaria: cozinhas ocultas, vidro inteligente e acabamentos naturais.","image":"https://images.unsplash.com/photo-1618220179428-22790b461013?w=1200&q=85"}'::jsonb
  ),

  -- 3. Post sobre Marcenaria Corporativa
  (
    'Marcenaria Corporativa: Como a Madeira Transforma a Produtividade',
    'marcenaria-corporativa-produtividade',
    'Estudos mostram que ambientes com elementos naturais aumentam a produtividade em até 15%. Saiba como a marcenaria de alto padrão pode transformar seu escritório.',
    'O mercado corporativo brasileiro está redescoberindo o valor da marcenaria de alto padrão. Não por estética, mas por resultados mensuráveis.\n\n## O Fator Biofilia\n\nEstudos da Universidade de Harvard mostram que ambientes com elementos naturais — madeira, pedra, vegetação — aumentam a produtividade em até 15% e reduzem o absenteísmo em 23%.\n\n### Por que a madeira funciona?\n\nA madeira não é apenas um material — é um regulador térmico e acústico natural. Ambientes revestidos em madeira mantêm temperatura mais estável, absorvem ruídos e reduzem o estresse.\n\n## Ambientes que Funcionam\n\n### 1. Salas de Reunião\n\nMesas orgânicas em madeira maciça eliminam hierarquias visuais. Ao contrário das mesas retangulares tradicionais — que têm um chefe na cabeceira — as mesas orgânicas permitem que todos se vejam igualmente.\n\n### 2. Cabines de Foco (Phone Booths)\n\nProfissionais de tecnologia passam em média 2,3 horas por dia em chamadas e videoconferências. Cabines acústicas revestidas em madeira oferecem privacidade sem isolamento social.\n\n### 3. Recepções Marcantes\n\nA recepção é o primeiro contato físico que um cliente tem com sua empresa. Um balcão monolítico em madeira com design escultórico comunica imediatamente o nível de sofisticação da marca.\n\n## Projetos que Fizemos\n\n> "A nova sede reduziu em 30% o turnover de talentos e foi eleita o melhor escritório do ano."\n> — Head de RH, empresa de tecnologia\n\n## Cases de Sucesso\n\n- **Headquarters Tech (1200 m²)**: Produtividade aumentou 18% após a mudança\n- **Grupo Financeiro (200 m²)**: 12 salas de diretoria convertidas para o padrão orgânico\n- **Escritório de Advocacia (180 m²)**: Percepção de sofisticação elevada em pesquisa com clientes\n\n## ROI da Marcenaria Corporativa\n\n| Investimento | Retorno estimado | Prazo |\n|-------------|-----------------|-------|\n| Recepção | 40% mais leads convertidos na visita | 6 meses |\n| Salas de reunião | 25% mais reuniões produtivas | Imediato |\n| Cabines de foco | 30% menos interrupções | 3 meses |\n| Estações flexíveis | 20% de economia em reformas futuras | 2 anos |\n\n## Conclusão\n\nInvestir em marcenaria corporativa não é despesa — é investimento em capital humano. A madeira transforma o ambiente de trabalho em uma vantagem competitiva real.',
    'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=85',
    'Sala de reunião corporativa com mesa orgânica em madeira',
    7, '{corporativo,escritório,produtividade,marcenaria,design}'::text[],
    'Felipe Amorim', true, false, now() - interval '7 days',
    '{"title":"Marcenaria Corporativa: Produtividade com Design","description":"Ambientes com madeira aumentam produtividade em até 15%. Descubra como a marcenaria de alto padrão transforma escritórios.","image":"https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=85"}'::jsonb
  ),

  -- 4. Post sobre Cozinhas
  (
    'Cozinha dos Sonhos: Como Planejar o Coração da Sua Casa',
    'cozinha-dos-sonhos-planejamento',
    'Guia completo para projetar a cozinha perfeita: do briefing ao acabamento, passando por ferragens, iluminação e os melhores materiais.',
    'A cozinha é o ambiente mais complexo de uma residência. Envolve hidráulica, elétrica, ventilação, circulação e armazenamento — tudo em um espaço que precisa ser bonito, funcional e durável.\n\n## Passo 1: Briefing Funcional\n\nAntes de pensar em materiais e estética, responda às perguntas certas:\n\n- Quantas pessoas cozinham simultaneamente?\n- Com que frequência recebem convidados?\n- Preferem eletrodomésticos embutidos ou aparentes?\n- Qual o orçamento destinado a ferragens?\n\n### O Triângulo Funcional\n\nO conceito clássico de cozinha — geladeira, fogão, pia — ainda é válido, mas evoluiu. Hoje trabalhamos com zonas:\n\n1. **Zona de estocagem** (geladeira, despensa seca)\n2. **Zona de preparo** (bancada, cortadores, temperos)\n3. **Zona de cocção** (fogão, forno, exaustão)\n4. **Zona de limpeza** (pia, lava-louças, lixo)\n5. **Zona de serviço** (cafeteira, micro-ondas, cooktop rápido)\n\n## Passo 2: Escolha dos Materiais\n\n### Madeira\n\n- **Freijó**: Versátil, tom médio, ótimo custo-benefício\n- **Carvalho Americano**: Resistente, veios marcantes, ideal para cozinhas\n- **Tauari**: Alternativa sustentável ao mogno, alta durabilidade\n- **MDF Naval**: Indispensável em áreas com umidade, reveste portas e gavetas\n\n### Ferragens\n\nPara cozinhas de alto padrão, não economize nas ferragens:\n\n```\nSistema de correr (portas escamoteáveis): R$ 3.000 - R$ 8.000 por módulo\nAmortecedores Blum: R$ 80 - R$ 150 por gaveta\nTouch-to-open magnético: R$ 200 - R$ 400 por porta\nElevador de coluna (forno/cafeteira): R$ 1.500 - R$ 3.000\n```\n\n## Passo 3: Iluminação por Camadas\n\nA cozinha exige três camadas de iluminação:\n\n- **Luz geral**: Plafons ou spots embutidos no teto\n- **Luz de tarefa**: Fitas de LED sob os armários superiores\n- **Luz de destaque**: Nichos iluminados, vitrines, prateleiras\n\n## Passo 4: O Toque Final\n\nOs detalhes que fazem a diferença:\n\n- **Puxadores**: Invísiveis (touch-to-open) são a tendência máxima\n- **Tomadas**: Réguas retráteis embutidas na bancada\n- **Abertura de portas**: Sensor de movimento para mãos ocupadas\n- **Proteção**: Película antivandalismo em tampos de vidro\n\n## Conclusão\n\nUma cozinha planejada dura de 15 a 20 anos. O investimento em marcenaria de qualidade se paga na durabilidade, na funcionalidade e no prazer de cozinhar em um espaço que funciona perfeitamente.',
    'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=85',
    'Cozinha gourmet planejada com ilha central',
    6, '{cozinha,planejamento,guia,marcenaria,ferragens}'::text[],
    'Felipe Amorim', true, false, now() - interval '4 days',
    '{"title":"Cozinha dos Sonhos: Guia Completo de Planejamento","description":"Do briefing ao acabamento: guia completo para projetar a cozinha perfeita com marcenaria de alto padrão, ferragens e iluminação.","image":"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=85"}'::jsonb
  ),

  -- 5. Post sobre Closets
  (
    'Closet dos Sonhos: Organização com Estilo e Tecnologia',
    'closet-dos-sonhos-organizacao',
    'Do vidro inteligente à iluminação circadiana — descubra as inovações que estão transformando closets em experiências de luxo diário.',
    'O closet deixou de ser um cômodo secundário para se tornar um dos espaços mais importantes da casa — e um dos que mais valorizam o imóvel.\n\n## Por que Investir em um Closet Planejado?\n\nSegundo pesquisa de mercado, imóveis com closets planejados valorizam até 12% a mais na revenda. Mas o valor real está no uso diário: um closet bem projetado economiza tempo, preserva as peças e transforma o ritual de se vestir em um momento de prazer.\n\n## 1. Layout: O Triângulo do Closet\n\nAssim como na cozinha, o closet tem zonas:\n\n- **Zona de armazenamento**: Roupas penduradas, dobradas, sapatos, acessórios\n- **Zona de experimentação**: Espelho, banco, luz focada\n- **Zona de preparação**: Gavetas para joias, relógios, perfumes\n\n### Dimensionamento\n\n| Tipo de peça | Altura do módulo | Profundidade |\n|-------------|-----------------|-------------|\n| Camisas/social | 100 cm | 55 cm |\n| Vestidos longos | 150 cm | 55 cm |\n| Calças (esticadas) | 120 cm | 35 cm |\n| Sapatos femininos | 25 cm por par | 35 cm |\n| Sapatos masculinos | 30 cm por par | 35 cm |\n\n## 2. Vidro Inteligente (Smart Glass)\n\nA tecnologia que mais impressiona no mercado atual. O vidro muda de transparente para opaco com um toque:\n\n- **Modo público**: Transparente, exibindo o acervo organizado\n- **Modo privado**: Opaco, escondendo o conteúdo\n- **Modo noturno**: Iluminação interna com efeito vitrine\n\n### Custos\n\nO smart glass ainda é um investimento alto (R$ 3.000 a R$ 6.000 por m² instalado), mas o impacto é incomparável.\n\n## 3. Iluminação Circadiana\n\nSistemas de LED com temperatura ajustável que acompanham o ciclo natural do corpo humano:\n\n- **Manhã (6500K)**: Luz branca fria que desperta\n- **Tarde (4000K)**: Luz neutra para escolha das peças\n- **Noite (2700K)**: Luz âmbar quente que relaxa\n\n## 4. Acessórios que Fazem a Diferença\n\n- **Calceiros automáticos**: Gavetas que organizam gravatas e cintos\n- **Lavanderias ocultas**: Módulo com varal retrátil e tábua de passar embutida\n- **Tomadas USB-C**: Embutidas em gavetas de acessórios\n- **Sapatários inclinados**: Exposição dos sapatos em ângulo de 15°\n\n## Conclusão\n\nO closet dos sonhos é aquele que equilibra tecnologia, organização e beleza. Com o planejamento certo, seu closet se torna não apenas um espaço de armazenamento, mas um ambiente que eleva sua rotina a um padrão de hotel cinco estrelas.',
    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=85',
    'Closet planejado com vidro inteligente e iluminação',
    5, '{closet,organização,tecnologia,design,marcenaria}'::text[],
    'Felipe Amorim', true, false, now() - interval '2 days',
    '{"title":"Closet dos Sonhos: Guia de Organização e Tecnologia","description":"Vidro inteligente, iluminação circadiana e design: as inovações que transformam closets em experiências de luxo diário.","image":"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=85"}'::jsonb
  )
on conflict (slug) do nothing;
